/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq.tables.records;


import javax.annotation.Generated;

import jobabroad.jooq.tables.AppliedJobs;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppliedJobsRecord extends UpdatableRecordImpl<AppliedJobsRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1914691988;

    /**
     * Setter for <code>jobabroad.applied_jobs.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobabroad.applied_jobs.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobabroad.applied_jobs.id_job</code>.
     */
    public void setIdJob(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobabroad.applied_jobs.id_job</code>.
     */
    public Integer getIdJob() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jobabroad.applied_jobs.applied</code>.
     */
    public void setApplied(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobabroad.applied_jobs.applied</code>.
     */
    public Integer getApplied() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AppliedJobs.APPLIED_JOBS.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AppliedJobs.APPLIED_JOBS.ID_JOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AppliedJobs.APPLIED_JOBS.APPLIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdJob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getApplied();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdJob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getApplied();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppliedJobsRecord value1(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppliedJobsRecord value2(Integer value) {
        setIdJob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppliedJobsRecord value3(Integer value) {
        setApplied(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppliedJobsRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppliedJobsRecord
     */
    public AppliedJobsRecord() {
        super(AppliedJobs.APPLIED_JOBS);
    }

    /**
     * Create a detached, initialised AppliedJobsRecord
     */
    public AppliedJobsRecord(Integer idUser, Integer idJob, Integer applied) {
        super(AppliedJobs.APPLIED_JOBS);

        set(0, idUser);
        set(1, idJob);
        set(2, applied);
    }
}
