/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq.tables.records;


import javax.annotation.Generated;

import jobabroad.jooq.tables.JobsSkills;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsSkillsRecord extends UpdatableRecordImpl<JobsSkillsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -788724659;

    /**
     * Setter for <code>jobabroad.jobs_skills.id_job</code>.
     */
    public void setIdJob(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobabroad.jobs_skills.id_job</code>.
     */
    public Integer getIdJob() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobabroad.jobs_skills.id_skill</code>.
     */
    public void setIdSkill(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobabroad.jobs_skills.id_skill</code>.
     */
    public Integer getIdSkill() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobsSkills.JOBS_SKILLS.ID_JOB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return JobsSkills.JOBS_SKILLS.ID_SKILL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdJob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdJob();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdSkill();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsSkillsRecord value1(Integer value) {
        setIdJob(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsSkillsRecord value2(Integer value) {
        setIdSkill(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsSkillsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobsSkillsRecord
     */
    public JobsSkillsRecord() {
        super(JobsSkills.JOBS_SKILLS);
    }

    /**
     * Create a detached, initialised JobsSkillsRecord
     */
    public JobsSkillsRecord(Integer idJob, Integer idSkill) {
        super(JobsSkills.JOBS_SKILLS);

        set(0, idJob);
        set(1, idSkill);
    }
}
