/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq.tables.records;


import javax.annotation.Generated;

import jobabroad.jooq.tables.PersonalExperience;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonalExperienceRecord extends UpdatableRecordImpl<PersonalExperienceRecord> implements Record5<Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = -1556457928;

    /**
     * Setter for <code>jobabroad.personal_experience.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobabroad.personal_experience.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jobabroad.personal_experience.id_user</code>.
     */
    public void setIdUser(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobabroad.personal_experience.id_user</code>.
     */
    public Integer getIdUser() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jobabroad.personal_experience.description_exp</code>.
     */
    public void setDescriptionExp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobabroad.personal_experience.description_exp</code>.
     */
    public String getDescriptionExp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jobabroad.personal_experience.years_exp</code>.
     */
    public void setYearsExp(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobabroad.personal_experience.years_exp</code>.
     */
    public Integer getYearsExp() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jobabroad.personal_experience.type_exp</code>.
     */
    public void setTypeExp(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobabroad.personal_experience.type_exp</code>.
     */
    public Integer getTypeExp() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PersonalExperience.PERSONAL_EXPERIENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PersonalExperience.PERSONAL_EXPERIENCE.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PersonalExperience.PERSONAL_EXPERIENCE.DESCRIPTION_EXP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PersonalExperience.PERSONAL_EXPERIENCE.YEARS_EXP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PersonalExperience.PERSONAL_EXPERIENCE.TYPE_EXP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescriptionExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getYearsExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTypeExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescriptionExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getYearsExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTypeExp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord value2(Integer value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord value3(String value) {
        setDescriptionExp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord value4(Integer value) {
        setYearsExp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord value5(Integer value) {
        setTypeExp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersonalExperienceRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonalExperienceRecord
     */
    public PersonalExperienceRecord() {
        super(PersonalExperience.PERSONAL_EXPERIENCE);
    }

    /**
     * Create a detached, initialised PersonalExperienceRecord
     */
    public PersonalExperienceRecord(Integer id, Integer idUser, String descriptionExp, Integer yearsExp, Integer typeExp) {
        super(PersonalExperience.PERSONAL_EXPERIENCE);

        set(0, id);
        set(1, idUser);
        set(2, descriptionExp);
        set(3, yearsExp);
        set(4, typeExp);
    }
}
