/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq;


import javax.annotation.Generated;

import jobabroad.jooq.tables.AppliedJobs;
import jobabroad.jooq.tables.Company;
import jobabroad.jooq.tables.Jobs;
import jobabroad.jooq.tables.JobsSkills;
import jobabroad.jooq.tables.PersonalExperience;
import jobabroad.jooq.tables.Resume;
import jobabroad.jooq.tables.Skills;
import jobabroad.jooq.tables.User;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jobabroad</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPLIED_JOBS_ID_JOB = Indexes0.APPLIED_JOBS_ID_JOB;
    public static final Index APPLIED_JOBS_PRIMARY = Indexes0.APPLIED_JOBS_PRIMARY;
    public static final Index COMPANY_PRIMARY = Indexes0.COMPANY_PRIMARY;
    public static final Index JOBS_COMPANY_ID = Indexes0.JOBS_COMPANY_ID;
    public static final Index JOBS_PRIMARY = Indexes0.JOBS_PRIMARY;
    public static final Index JOBS_SKILLS_ID_SKILL = Indexes0.JOBS_SKILLS_ID_SKILL;
    public static final Index JOBS_SKILLS_PRIMARY = Indexes0.JOBS_SKILLS_PRIMARY;
    public static final Index PERSONAL_EXPERIENCE_ID_USER = Indexes0.PERSONAL_EXPERIENCE_ID_USER;
    public static final Index PERSONAL_EXPERIENCE_PRIMARY = Indexes0.PERSONAL_EXPERIENCE_PRIMARY;
    public static final Index RESUME_PRIMARY = Indexes0.RESUME_PRIMARY;
    public static final Index SKILLS_PRIMARY = Indexes0.SKILLS_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APPLIED_JOBS_ID_JOB = Internal.createIndex("id_job", AppliedJobs.APPLIED_JOBS, new OrderField[] { AppliedJobs.APPLIED_JOBS.ID_JOB }, false);
        public static Index APPLIED_JOBS_PRIMARY = Internal.createIndex("PRIMARY", AppliedJobs.APPLIED_JOBS, new OrderField[] { AppliedJobs.APPLIED_JOBS.ID_USER, AppliedJobs.APPLIED_JOBS.ID_JOB }, true);
        public static Index COMPANY_PRIMARY = Internal.createIndex("PRIMARY", Company.COMPANY, new OrderField[] { Company.COMPANY.ID }, true);
        public static Index JOBS_COMPANY_ID = Internal.createIndex("company_id", Jobs.JOBS, new OrderField[] { Jobs.JOBS.COMPANY_ID }, false);
        public static Index JOBS_PRIMARY = Internal.createIndex("PRIMARY", Jobs.JOBS, new OrderField[] { Jobs.JOBS.ID }, true);
        public static Index JOBS_SKILLS_ID_SKILL = Internal.createIndex("id_skill", JobsSkills.JOBS_SKILLS, new OrderField[] { JobsSkills.JOBS_SKILLS.ID_SKILL }, false);
        public static Index JOBS_SKILLS_PRIMARY = Internal.createIndex("PRIMARY", JobsSkills.JOBS_SKILLS, new OrderField[] { JobsSkills.JOBS_SKILLS.ID_JOB, JobsSkills.JOBS_SKILLS.ID_SKILL }, true);
        public static Index PERSONAL_EXPERIENCE_ID_USER = Internal.createIndex("id_user", PersonalExperience.PERSONAL_EXPERIENCE, new OrderField[] { PersonalExperience.PERSONAL_EXPERIENCE.ID_USER }, false);
        public static Index PERSONAL_EXPERIENCE_PRIMARY = Internal.createIndex("PRIMARY", PersonalExperience.PERSONAL_EXPERIENCE, new OrderField[] { PersonalExperience.PERSONAL_EXPERIENCE.ID }, true);
        public static Index RESUME_PRIMARY = Internal.createIndex("PRIMARY", Resume.RESUME, new OrderField[] { Resume.RESUME.ID_USER }, true);
        public static Index SKILLS_PRIMARY = Internal.createIndex("PRIMARY", Skills.SKILLS, new OrderField[] { Skills.SKILLS.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
