/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jobabroad.jooq.tables.AppliedJobs;
import jobabroad.jooq.tables.Company;
import jobabroad.jooq.tables.Jobs;
import jobabroad.jooq.tables.JobsSkills;
import jobabroad.jooq.tables.PersonalExperience;
import jobabroad.jooq.tables.Resume;
import jobabroad.jooq.tables.Skills;
import jobabroad.jooq.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jobabroad extends SchemaImpl {

    private static final long serialVersionUID = -2061627825;

    /**
     * The reference instance of <code>jobabroad</code>
     */
    public static final Jobabroad JOBABROAD = new Jobabroad();

    /**
     * The table <code>jobabroad.applied_jobs</code>.
     */
    public final AppliedJobs APPLIED_JOBS = jobabroad.jooq.tables.AppliedJobs.APPLIED_JOBS;

    /**
     * The table <code>jobabroad.company</code>.
     */
    public final Company COMPANY = jobabroad.jooq.tables.Company.COMPANY;

    /**
     * The table <code>jobabroad.jobs</code>.
     */
    public final Jobs JOBS = jobabroad.jooq.tables.Jobs.JOBS;

    /**
     * The table <code>jobabroad.jobs_skills</code>.
     */
    public final JobsSkills JOBS_SKILLS = jobabroad.jooq.tables.JobsSkills.JOBS_SKILLS;

    /**
     * The table <code>jobabroad.personal_experience</code>.
     */
    public final PersonalExperience PERSONAL_EXPERIENCE = jobabroad.jooq.tables.PersonalExperience.PERSONAL_EXPERIENCE;

    /**
     * The table <code>jobabroad.resume</code>.
     */
    public final Resume RESUME = jobabroad.jooq.tables.Resume.RESUME;

    /**
     * The table <code>jobabroad.skills</code>.
     */
    public final Skills SKILLS = jobabroad.jooq.tables.Skills.SKILLS;

    /**
     * The table <code>jobabroad.user</code>.
     */
    public final User USER = jobabroad.jooq.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Jobabroad() {
        super("jobabroad", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AppliedJobs.APPLIED_JOBS,
            Company.COMPANY,
            Jobs.JOBS,
            JobsSkills.JOBS_SKILLS,
            PersonalExperience.PERSONAL_EXPERIENCE,
            Resume.RESUME,
            Skills.SKILLS,
            User.USER);
    }
}
