/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq;


import javax.annotation.Generated;

import jobabroad.jooq.tables.AppliedJobs;
import jobabroad.jooq.tables.Company;
import jobabroad.jooq.tables.Jobs;
import jobabroad.jooq.tables.JobsSkills;
import jobabroad.jooq.tables.PersonalExperience;
import jobabroad.jooq.tables.Resume;
import jobabroad.jooq.tables.Skills;
import jobabroad.jooq.tables.User;
import jobabroad.jooq.tables.records.AppliedJobsRecord;
import jobabroad.jooq.tables.records.CompanyRecord;
import jobabroad.jooq.tables.records.JobsRecord;
import jobabroad.jooq.tables.records.JobsSkillsRecord;
import jobabroad.jooq.tables.records.PersonalExperienceRecord;
import jobabroad.jooq.tables.records.ResumeRecord;
import jobabroad.jooq.tables.records.SkillsRecord;
import jobabroad.jooq.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jobabroad</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppliedJobsRecord> KEY_APPLIED_JOBS_PRIMARY = UniqueKeys0.KEY_APPLIED_JOBS_PRIMARY;
    public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = UniqueKeys0.KEY_COMPANY_PRIMARY;
    public static final UniqueKey<JobsRecord> KEY_JOBS_PRIMARY = UniqueKeys0.KEY_JOBS_PRIMARY;
    public static final UniqueKey<JobsSkillsRecord> KEY_JOBS_SKILLS_PRIMARY = UniqueKeys0.KEY_JOBS_SKILLS_PRIMARY;
    public static final UniqueKey<PersonalExperienceRecord> KEY_PERSONAL_EXPERIENCE_PRIMARY = UniqueKeys0.KEY_PERSONAL_EXPERIENCE_PRIMARY;
    public static final UniqueKey<ResumeRecord> KEY_RESUME_PRIMARY = UniqueKeys0.KEY_RESUME_PRIMARY;
    public static final UniqueKey<SkillsRecord> KEY_SKILLS_PRIMARY = UniqueKeys0.KEY_SKILLS_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppliedJobsRecord, UserRecord> APPLIED_JOBS_IBFK_1 = ForeignKeys0.APPLIED_JOBS_IBFK_1;
    public static final ForeignKey<AppliedJobsRecord, JobsRecord> APPLIED_JOBS_IBFK_2 = ForeignKeys0.APPLIED_JOBS_IBFK_2;
    public static final ForeignKey<JobsRecord, CompanyRecord> JOBS_IBFK_1 = ForeignKeys0.JOBS_IBFK_1;
    public static final ForeignKey<JobsSkillsRecord, JobsRecord> JOBS_SKILLS_IBFK_1 = ForeignKeys0.JOBS_SKILLS_IBFK_1;
    public static final ForeignKey<JobsSkillsRecord, SkillsRecord> JOBS_SKILLS_IBFK_2 = ForeignKeys0.JOBS_SKILLS_IBFK_2;
    public static final ForeignKey<PersonalExperienceRecord, UserRecord> PERSONAL_EXPERIENCE_IBFK_1 = ForeignKeys0.PERSONAL_EXPERIENCE_IBFK_1;
    public static final ForeignKey<ResumeRecord, UserRecord> RESUME_IBFK_1 = ForeignKeys0.RESUME_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<UserRecord, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AppliedJobsRecord> KEY_APPLIED_JOBS_PRIMARY = Internal.createUniqueKey(AppliedJobs.APPLIED_JOBS, "KEY_applied_jobs_PRIMARY", AppliedJobs.APPLIED_JOBS.ID_USER, AppliedJobs.APPLIED_JOBS.ID_JOB);
        public static final UniqueKey<CompanyRecord> KEY_COMPANY_PRIMARY = Internal.createUniqueKey(Company.COMPANY, "KEY_company_PRIMARY", Company.COMPANY.ID);
        public static final UniqueKey<JobsRecord> KEY_JOBS_PRIMARY = Internal.createUniqueKey(Jobs.JOBS, "KEY_jobs_PRIMARY", Jobs.JOBS.ID);
        public static final UniqueKey<JobsSkillsRecord> KEY_JOBS_SKILLS_PRIMARY = Internal.createUniqueKey(JobsSkills.JOBS_SKILLS, "KEY_jobs_skills_PRIMARY", JobsSkills.JOBS_SKILLS.ID_JOB, JobsSkills.JOBS_SKILLS.ID_SKILL);
        public static final UniqueKey<PersonalExperienceRecord> KEY_PERSONAL_EXPERIENCE_PRIMARY = Internal.createUniqueKey(PersonalExperience.PERSONAL_EXPERIENCE, "KEY_personal_experience_PRIMARY", PersonalExperience.PERSONAL_EXPERIENCE.ID);
        public static final UniqueKey<ResumeRecord> KEY_RESUME_PRIMARY = Internal.createUniqueKey(Resume.RESUME, "KEY_resume_PRIMARY", Resume.RESUME.ID_USER);
        public static final UniqueKey<SkillsRecord> KEY_SKILLS_PRIMARY = Internal.createUniqueKey(Skills.SKILLS, "KEY_skills_PRIMARY", Skills.SKILLS.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AppliedJobsRecord, UserRecord> APPLIED_JOBS_IBFK_1 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_USER_PRIMARY, AppliedJobs.APPLIED_JOBS, "applied_jobs_ibfk_1", AppliedJobs.APPLIED_JOBS.ID_USER);
        public static final ForeignKey<AppliedJobsRecord, JobsRecord> APPLIED_JOBS_IBFK_2 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_JOBS_PRIMARY, AppliedJobs.APPLIED_JOBS, "applied_jobs_ibfk_2", AppliedJobs.APPLIED_JOBS.ID_JOB);
        public static final ForeignKey<JobsRecord, CompanyRecord> JOBS_IBFK_1 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_COMPANY_PRIMARY, Jobs.JOBS, "jobs_ibfk_1", Jobs.JOBS.COMPANY_ID);
        public static final ForeignKey<JobsSkillsRecord, JobsRecord> JOBS_SKILLS_IBFK_1 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_JOBS_PRIMARY, JobsSkills.JOBS_SKILLS, "jobs_skills_ibfk_1", JobsSkills.JOBS_SKILLS.ID_JOB);
        public static final ForeignKey<JobsSkillsRecord, SkillsRecord> JOBS_SKILLS_IBFK_2 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_SKILLS_PRIMARY, JobsSkills.JOBS_SKILLS, "jobs_skills_ibfk_2", JobsSkills.JOBS_SKILLS.ID_SKILL);
        public static final ForeignKey<PersonalExperienceRecord, UserRecord> PERSONAL_EXPERIENCE_IBFK_1 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_USER_PRIMARY, PersonalExperience.PERSONAL_EXPERIENCE, "personal_experience_ibfk_1", PersonalExperience.PERSONAL_EXPERIENCE.ID_USER);
        public static final ForeignKey<ResumeRecord, UserRecord> RESUME_IBFK_1 = Internal.createForeignKey(jobabroad.jooq.Keys.KEY_USER_PRIMARY, Resume.RESUME, "resume_ibfk_1", Resume.RESUME.ID_USER);
    }
}
