/*
 * This file is generated by jOOQ.
 */
package jobabroad.jooq;


import javax.annotation.Generated;

import jobabroad.jooq.tables.AppliedJobs;
import jobabroad.jooq.tables.Company;
import jobabroad.jooq.tables.Jobs;
import jobabroad.jooq.tables.JobsSkills;
import jobabroad.jooq.tables.PersonalExperience;
import jobabroad.jooq.tables.Resume;
import jobabroad.jooq.tables.Skills;
import jobabroad.jooq.tables.User;


/**
 * Convenience access to all tables in jobabroad
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jobabroad.applied_jobs</code>.
     */
    public static final AppliedJobs APPLIED_JOBS = jobabroad.jooq.tables.AppliedJobs.APPLIED_JOBS;

    /**
     * The table <code>jobabroad.company</code>.
     */
    public static final Company COMPANY = jobabroad.jooq.tables.Company.COMPANY;

    /**
     * The table <code>jobabroad.jobs</code>.
     */
    public static final Jobs JOBS = jobabroad.jooq.tables.Jobs.JOBS;

    /**
     * The table <code>jobabroad.jobs_skills</code>.
     */
    public static final JobsSkills JOBS_SKILLS = jobabroad.jooq.tables.JobsSkills.JOBS_SKILLS;

    /**
     * The table <code>jobabroad.personal_experience</code>.
     */
    public static final PersonalExperience PERSONAL_EXPERIENCE = jobabroad.jooq.tables.PersonalExperience.PERSONAL_EXPERIENCE;

    /**
     * The table <code>jobabroad.resume</code>.
     */
    public static final Resume RESUME = jobabroad.jooq.tables.Resume.RESUME;

    /**
     * The table <code>jobabroad.skills</code>.
     */
    public static final Skills SKILLS = jobabroad.jooq.tables.Skills.SKILLS;

    /**
     * The table <code>jobabroad.user</code>.
     */
    public static final User USER = jobabroad.jooq.tables.User.USER;
}
